$PROJECT_ROOT = "$(Get-Location)"
$BUILD_DIR = "$(Get-Location)\build"
$DYNAMORIO_ROOT = "$(Get-Location)\..\dynamorio"
$DYNAMORIO_DIR = "$(Get-Location)\..\dynamorio\cmake"
$DRMEMORY_DIR = "$(Get-Location)\..\dynamorio\drmemory\drmf"